import asyncio
import sys
from temporalio.client import Client
from workflows import CityGuideAgent 

import uuid
# ...imports...

async def main():
    if len(sys.argv) > 1:
        city = sys.argv[1]
    else:
        city = "Paris" # Let's use a fun default

    # Connect to server
    client = await Client.connect("localhost:7233")

    print(f" waking up the Agent for: {city}...")
    
    # 3. Start the Agent
    # Notice we changed the workflow name to 'CityGuideAgent'
    # We add a UUID to ensure unique IDs for every run during dev
    run_id = str(uuid.uuid4())[:8]
    handle = await client.start_workflow(
        CityGuideAgent,
        city,
        id=f"city-guide-agent-{city.replace(' ', '-').lower()}-{run_id}",
        task_queue="city-guide-queue",
    )

    print(f"Agent started! Workflow ID: {handle.id}")
    print(f"View progress at: http://localhost:8233/namespaces/default/workflows/{handle.id}")

    # Wait for result
    result = await handle.result()

    print("\n" + "=" * 50)
    print("FINAL GUIDE (Generated by Temporal Agent)")
    print("=" * 50 + "\n")
    print(result)

if __name__ == "__main__":
    asyncio.run(main())